name: Build OCMOD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ocmod.zip directly
      run: zip -r ocmod.zip * -x '*.git*' '.github/*'

    - name: Upload ocmod.zip directly
      uses: actions/upload-artifact@v3
      with:
        name: api-mrBin.ocmod.zip
        path: ocmod.zip
