name: Build OCMOD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Zip OCMOD files
      run: |
        mkdir -p build
        zip -r build/ocmod.zip * -x '*.git*' '.github/*'

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ocmod.zip
        path: build/ocmod.zip
