name: Build OCMOD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up build folder
      run: mkdir -p build

    - name: Zip OCMOD files directly
      run: zip -r build/ocmod.zip * -x '*.git*' '.github/*'

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ocmod.zip
        path: build/ocmod.zip
